export const SERVER_EVENT = {
  // Global
  LOGIN: 'LOGIN',
  MESSAGE_SERVER: 'MESSAGE_SERVER',

  // Room
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  MESSAGE_ROOM: 'MESSAGE_ROOM',

  // Game
  TOGGLE_READY: 'TOGGLE_READY',
  UPDATE_DIR: 'UPDATE_DIR'
};

export const CLIENT_EVENT = {
  // Global
  MESSAGE_SERVER: 'MESSAGE_SERVER',
  UPDATE_ROOMS: 'UPDATE_ROOMS',

  // Room
  UPDATE_ROOM: 'UPDATE_ROOM',
  UPDATE_GAME: 'UPDATE_GAME',
  MESSAGE: 'MESSAGE'
};
